all:
  children:
    bigip_devices:
      hosts:
        bigip-prod-01.example.com:
          ansible_host: 192.168.1.10
          ansible_connection: local
        bigip-prod-02.example.com:
          ansible_host: 192.168.1.11
          ansible_connection: local
