galaxy_info:
  author: mlowcher
  description: Automated SSL certificate renewal for F5 BIG-IP via DigiCert CertCentral
  license: MIT
  min_ansible_version: "2.14"

collections:
  - community.crypto
  - f5networks.f5_modules
  - ansible.utils
  - servicenow.itsm
